# Auto-generated by Pandomium-Builder.jar
mvn install:install-file\ 
  -Dpackaging=jar\ 
  -Dfile=jcef-win32-fat.jar\ 
  -DgroupId=org.panda-lang.pandomium-fat-jars\ 
  -DartifactId=jcef-win32-fat\ 
  -Dversion=81.2 

mvn install:install-file\ 
  -Dpackaging=jar\ 
  -Dfile=jcef-win64-fat.jar\ 
  -DgroupId=org.panda-lang.pandomium-fat-jars\ 
  -DartifactId=jcef-win64-fat\ 
  -Dversion=81.2 
