# Auto-generated by Pandomium-Builder.jar

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-win32-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-win32-fat \
                       -Dversion=1.1.1-JCEF-v1.0.10-92.0.25+gd15cfa8+chromium-92.0.4515.131 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-win64-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-win64-fat \
                       -Dversion=1.1.1-JCEF-v1.0.10-92.0.25+gd15cfa8+chromium-92.0.4515.131 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy
