# Auto-generated by Pandomium-Builder.jar

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-linux32-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-linux32-fat \
                       -Dversion=v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105-v2-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-linux64-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-linux64-fat \
                       -Dversion=v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105-v2-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-win32-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-win32-fat \
                       -Dversion=v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105-v2-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy:deploy-file -Durl=https://repo.panda-lang.org/releases\
                       -DrepositoryId=panda-repository \
                       -Dfile=jcef-win64-fat.jar \
                       -DgroupId=org.panda-lang.pandomium-fat-jars \
                       -DartifactId=jcef-win64-fat \
                       -Dversion=v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105-v2-JCEF-v1.0.10-84.3.8+gc8a556f+chromium-84.0.4147.105 \
                       -Dpackaging=jar \
                       -DgeneratePom=true \
                       -DgeneratePom.description="Contains OS-specific JCEF code." \

mvn --batch-mode deploy
