name: Create release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Peter'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clone pandonium repository
        uses: actions/checkout@v2
        
      - name: Download/Install JRE
        uses: actions/setup-java@v2
        with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '14'
         
      - name: Run Pandonium-Builder.jar
        run: | 
          cd ${{ github.workspace }} 
          java -jar Pandonium-Builder.jar o-auth-token:${{secrets.GITHUB_TOKEN}}
          
      # TODO actually create a release with actions and add assets via actions
      
      - name: Commit changes
        run: |
          git config --global user.name 'Update-JCEF-Action'
          git config --global user.email 'Update-JCEF-Action@users.noreply.github.com'
          git commit -am "Updated JCEF builds."
          git push
